A_a = M_a = '\xe1'
A_b = M_b = '\xe2'
A_c = M_c = '\xe3'
A_d = M_d = '\xe4'
A_e = M_e = '\xe5'
A_f = M_f = '\xe6'
A_g = M_g = '\xe7'
A_h = M_h = '\xe8'
A_i = M_i = '\xe9'
A_j = M_j = '\xea'
A_k = M_k = '\xeb'
A_l = M_l = '\xec'
A_m = M_m = '\xed'
A_n = M_n = '\xee'
A_o = M_o = '\xef'
A_p = M_p = '\xf0'
A_q = M_q = '\xf1'
A_r = M_r = '\xf2'
A_s = M_s = '\xf3'
A_t = M_t = '\xf4'
A_u = M_u = '\xf5'
A_v = M_v = '\xf6'
A_w = M_w = '\xf7'
A_x = M_x = '\xf8'
A_y = M_y = '\xf9'
A_z = M_z = '\xfa'

A_T = M_T = '\xd4'

M_backspace = '\x88'
